### ISSUE TITLE
Building failed

### ISSUE THREAD

**Issue by cyberboh** [j-hc/revanced-magisk-module#143]
**Twitch failed to build:**

`java -jar temp/revanced-cli-2.20.0-all.jar --rip-lib x86_64 --rip-lib x86 --temp-dir=temp/tmp.ckmElGGFkD -c -a temp/twitch-stock-v11.0.0.0005-all.apk -o temp/twitch-revanced-v11.0.0.0005-all.apk -b temp/revanced-patches-2.153.0.jar --keystore=ks.keystore   -m temp/revanced-integrations-0.92.2-v0.92.2.apk
INFO: Reading dex files 
org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Not a valid dex magic value: 3c 21 44 4f 43 54 59 50
	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:93)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:53)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:43)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:66)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:51)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:42)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:36)
	at app.revanced.patcher.Patcher.<init>(Patcher.kt:56)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:142)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
BUILDING 'Twitch' FAILED`

Warnweather too:
`Building 'WarnWetter' (all) in 'APK' mode
2023-01-12 05:43:39 URL:https://www.apkmirror.com/apk/appest-inc/deutscher-wetterdienst/warnwetter/ [241184] -> "-" [1]
2023-01-12 05:43:40 URL:https://www.apkmirror.com/uploads/?appcategory=warnwetter [274887] -> "-" [1]
Choosing version '4.0.7' (WarnWetter)
Downloading 'WarnWetter' from APKMirror
https://www.apkmirror.com/apk/appest-inc/deutscher-wetterdienst/warnwetter/warnwetter-4-0-7-release/:
2023-01-12 05:43:41 ERROR 404: Not Found.
ERROR: Could not find any release of 'WarnWetter' with the given version ('4.0.7') and regex
INFO: Copying youtube-revanced-v17.49.37-all-module_aligned.apk to youtube-revanced-v17.49.37-all-module.apk 
INFO: Cleaned up cache directory 
INFO: Finished 
~/work/revanced-magisk-module/revanced-magisk-module/temp/tmp.bdN9hb0NUG ~/work/revanced-magisk-module/revanced-magisk-module
Error: Process completed with exit code 1.`

**Comment by j-hc** [comment]
fixed 73b99fe02b6a7e4b9d785eda5bb8dab5d91debbd
