### ISSUE TITLE
Error: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by cyberboh** [j-hc/revanced-magisk-module#147]
Im getting error on building 

`Built YouTube (all) (root): 'build/youtube-revanced-magisk-v17.49.37-all.zip'
Error: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3537)
	at org.jf.dexlib2.writer.io.MemoryDataStore.growBufferIfNeeded(MemoryDataStore.java:61)
	at org.jf.dexlib2.writer.io.MemoryDataStore.access$000(MemoryDataStore.java:9)
	at org.jf.dexlib2.writer.io.MemoryDataStore$1.write(MemoryDataStore.java:49)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:148)
	at lanchon.multidexlib2.DexIO.lambda$writeMultiDexDirectoryMultiThread$0(DexIO.java:92)
	at lanchon.multidexlib2.DexIO$$Lambda$57/0x00000008012c5fe0.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by j-hc** [comment]
what is your config

**Comment by cyberboh** [comment]
> what is your config

this my config https://github.com/cyberboh/revanced-magisk-module/commit/4b6d9dfb402f2f57fbb23c1d59bf3ff72e4b091c

**Comment by cyberboh** [comment]
> what is your config

I updated my config here https://github.com/cyberboh/revanced-magisk-module/commit/3c89a718950919c4e1c495eb85edaf8ca2e8ea4b
still getting same issue
[full_logs_16.zip](https://github.com/j-hc/revanced-magisk-module/files/10419260/full_logs_16.zip)

**Comment by j-hc** [comment]
fixed with 1361887d0e503babe75c8e758bfc4bf985d3c168
