### ISSUE TITLE
Error when building Instagram and Twitter

### ISSUE THREAD

**Issue by gnadgnaoh** [j-hc/revanced-magisk-module#185]
**Describe the bug**
Twitter:
SEVERE: hide-timeline-ads failed: 
app.revanced.patcher.patch.PatchResultError: Failed to resolve ShowAdFingerprint
	at app.revanced.extensions.ExtensionsKt.toErrorResult(Extensions.kt:18)
	at app.revanced.patches.instagram.patches.ads.timeline.patch.HideTimelineAdsPatch.execute(HideTimelineAdsPatch.kt:39)
	at app.revanced.patches.instagram.patches.ads.timeline.patch.HideTimelineAdsPatch.execute(HideTimelineAdsPatch.kt:24)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:335)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:158)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
	Instagram:
	SEVERE: hide-timeline-ads failed: 
app.revanced.patcher.patch.PatchResultError: Failed to resolve ShowAdFingerprint
	at app.revanced.extensions.ExtensionsKt.toErrorResult(Extensions.kt:18)
	at app.revanced.patches.instagram.patches.ads.timeline.patch.HideTimelineAdsPatch.execute(HideTimelineAdsPatch.kt:39)
	at app.revanced.patches.instagram.patches.ads.timeline.patch.HideTimelineAdsPatch.execute(HideTimelineAdsPatch.kt:24)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:335)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:158)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
**DO NOT REPORT REVANCED BUGS IN THIS REPO**

**Comment by j-hc** [comment]
you didnt provide your config.toml and full build logs so im going to assume you are trying to patch incompatible versions. that i cant fix.

**Comment by gnadgnaoh** [comment]
> > DO NOT REPORT REVANCED BUGS IN THIS REPO
> 
> literally [revanced/revanced-patches#1630](https://github.com/revanced/revanced-patches/issues/1630) which is already fixed, but [not in stable releases yet](https://github.com/revanced/revanced-patches/pull/1664)
> 
> if you can't wait, you can try set `patches-version` in `config.toml` to anything newer than `v2.165.0-dev.3`

Thank you, After set patches-version its still have error

Need to set merge-integrations = true in config.tolm for Instagram and Twitter

@j-hc
