### ISSUE TITLE
Error building Twitter, failed on "hide-ads" and "hide-recommended-users"

### ISSUE THREAD

**Issue by belinux** [j-hc/revanced-magisk-module#225]
I already checked on the patch repo and it has been recommended to try on lower versions with the latest CLI, but I could not find a suitable version. 
Log:
```
2023-05-05 13:24:23 URL:https://www.apkmirror.com/apk/twitter-inc/twitter/ [299382] -> "-" [1]
2023-05-05 13:24:24 URL:https://www.apkmirror.com/uploads/?appcategory=twitter [267991] -> "-" [1]
[0;32m[+] Choosing version '9.87.0-release.0' (Twitter)[0m
[0;32m[+] Downloading 'Twitter' from APKMirror[0m
2023-05-05 13:24:26 URL:https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-9-87-0-release-0-release/ [236645] -> "-" [1]
2023-05-05 13:24:28 URL:https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-9-87-0-release-0-release/twitter-9-87-0-release-0-2-android-apk-download/ [279606] -> "-" [1]
2023-05-05 13:24:30 URL:https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-9-87-0-release-0-release/twitter-9-87-0-release-0-2-android-apk-download/download/?key=6fc094b2635d1596dc3a528302c620c9c8d4e9b9&forcebaseapk=true [266537] -> "-" [1]
2023-05-05 13:24:32 URL:https://downloadr2.apkmirror.com/wp-content/uploads/2023/05/67/6451f3118d9f4/com.twitter.android_9.87.0-release.0-29870000_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk?verify=1683285570-wWuToFOmdO5ha9Nmf9pNHtOk5GGe0TY2O11QEs1xxxQ [113479521/113479521] -> "temp/tmp.com.twitter.android-9.87.0-release.0-all.apk" [1]
[0;32m[+] Downloading 'Twitter' bundle from APKMirror[0m
2023-05-05 13:24:33 URL:https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-9-87-0-release-0-release/ [236645] -> "-" [1]
2023-05-05 13:24:34 URL:https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-9-87-0-release-0-release/twitter-9-87-0-release-0-android-apk-download/ [267861] -> "-" [1]
2023-05-05 13:24:35 URL:https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-9-87-0-release-0-release/twitter-9-87-0-release-0-android-apk-download/download/?key=3a188daae7b91b014d85adee7b02dc89dea4fc97&forcebaseapk=true [250156] -> "-" [1]
2023-05-05 13:24:36 URL:https://downloadr2.apkmirror.com/wp-content/uploads/2023/05/09/6451f317d6826/com.twitter.android_9.87.0-release.0-29870000_minAPI23(nodpi)_apkmirror.com.apk?verify=1683285575-x0KIJbeLOB619guX6aD9ByQ9jn9pW-4eNhG8q43aRow [35942994/35942994] -> "temp/tmp.com.twitter.android-9.87.0-release.0-all-bundle.apk" [1]
[0;32m[+] 'Twitter' bundle was downloaded successfully and will be used for the module[0m
[0;32m[+] Building 'Twitter' (all) in 'module' mode[0m
[0;32m[+] java -jar temp/tools-revanced/revanced-cli-2.22.0-all.jar --rip-lib x86_64 --rip-lib x86 --temp-dir=temp/tmp.4ZuH5AHvK5 -c -a temp/com.twitter.android-9.87.0-release.0-all.apk -o temp/twitter-revanced-9.87.0-release.0-all.apk -b temp/tools-revanced/revanced-patches-2.173.0.jar --keystore=ks.keystore -e hide-views-stats  -m temp/tools-revanced/revanced-integrations-0.107.0.apk --unsigned[0m
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping change-package-name: Excluded by default 
INFO: Skipping enable-android-debugging: Excluded by default 
INFO: Skipping export-all-activities: Excluded by default 
WARNING: Skipping hide-views-stats: Incompatible with version 9.87.0-release.0. This patch is only compatible with com.twitter.android: 9.69.1-release.0, 9.71.0-release.0 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping remove-screenshot-restriction: Excluded by default 
INFO: Skipping spoof-wifi-connection: Excluded by default 
INFO: Merging temp/tools-revanced/revanced-integrations-0.107.0.apk 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: dynamic-color succeeded 
SEVERE: hide-ads failed: 
app.revanced.patcher.patch.PatchResultError: 'hide-ads' depends on 'json-hook' but the following error was raised: Unexpected integrations.
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: hide-recommended-users failed: 
app.revanced.patcher.patch.PatchResultError: 'hide-recommended-users' depends on 'json-hook' but the following error was raised: 'json-hook' did not succeed previously
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: Compiling resources 
INFO: Writing modified dex files 
INFO: Aligning com.twitter.android-9.87.0-release.0-all.apk to twitter-revanced-9.87.0-release.0-all_aligned.apk 
INFO: Copying twitter-revanced-9.87.0-release.0-all_aligned.apk to twitter-revanced-9.87.0-release.0-all.apk 
INFO: Cleaned up cache directory 
INFO: Finished 
[0;32m[+] Packing module (Twitter)[0m
[0;32m[+] Built Twitter (all) (root): 'build/twitter-revanced-magisk-v9.87.0-release.0-all.zip'[0m
```

**Comment by j-hc** [comment]
revanced issue if anything
