### ISSUE TITLE
Show popup error after device reboot

### ISSUE THREAD

**Issue by bamzzz** [j-hc/revanced-magisk-module#227]
java.lang.ExceptionInInitializerError
	at app.revanced.integrations.settings.SettingsEnum.<init>(SettingsEnum.java:207)
	at app.revanced.integrations.settings.SettingsEnum.<clinit>(SettingsEnum.java:18)
	at app.revanced.integrations.patches.TabletMiniPlayerOverridePatch.getTabletMiniPlayerOverride(TabletMiniPlayerOverridePatch.java:8)
	at uyb.I(PG:1)
	at zea.J(PG:5)
	at zea.a(PG:17)
	at ataa.a(PG:1)
	at mor.a(PG:7)
	at mnx.run(PG:40)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean app.revanced.integrations.settings.SettingsEnum.getBoolean()' on a null object reference
	at app.revanced.integrations.utils.LogHelper.printException(LogHelper.java:128)
	at app.revanced.integrations.utils.LogHelper.printException(LogHelper.java:98)
	at app.revanced.integrations.utils.ReVancedUtils.getContext(ReVancedUtils.java:104)
	at app.revanced.integrations.settings.SharedPrefCategory.<init>(SharedPrefCategory.java:35)
	at app.revanced.integrations.settings.SharedPrefCategory.<clinit>(SharedPrefCategory.java:23)
	... 17 more

**Comment by j-hc** [comment]
if anything, revanced bug. if this happens with both magisk module or microg+apk, then you can reopen the issue.
