### ISSUE TITLE
Add options to provide api key to patch Infinity for Reddit in config.tolm

### ISSUE THREAD

**Issue by gnadgnaoh** [j-hc/revanced-magisk-module#275]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**
+] Building 'Infinity' in 'apk' mode
[+] java -jar temp/jhc-rv/revanced-cli-2.23.0-all.jar --rip-lib x86_64 --rip-lib x86 --temp-dir=temp/tmp.H3WHQ2jFmP -c -a temp/ml.docilealligator.infinityforreddit-6.0.2-all.apk -o temp/infinity-revanced-6.0.2-all.apk -b temp/revanced-rv/revanced-patches-2.184.0.jar --keystore=ks.keystore   --experimental -m temp/revanced-rv/revanced-integrations-0.112.0.apk
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping change-package-name: Excluded by default 
INFO: Skipping enable-android-debugging: Excluded by default 
INFO: Skipping export-all-activities: Excluded by default 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping remove-screen-capture-restriction: Excluded by default 
INFO: Skipping remove-screenshot-restriction: Excluded by default 
INFO: Skipping spoof-wifi-connection: Excluded by default 
INFO: Executing patches 
SEVERE: Change OAuth client id failed: 
app.revanced.patcher.patch.PatchResultError: No client ID provided
	at app.revanced.patches.reddit.customclients.AbstractChangeOAuthClientIdPatch.execute(AbstractChangeOAuthClientIdPatch.kt:22)
	at app.revanced.patches.reddit.customclients.AbstractChangeOAuthClientIdPatch.execute(AbstractChangeOAuthClientIdPatch.kt:11)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:333)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:173)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)

**Comment by j-hc** [comment]
use [rvmm-config-gen](https://j-hc.github.io/rvmm-config-gen/) to generate options.json
