### ISSUE TITLE
Building Music is failing

### ISSUE THREAD

**Issue by vcdwelt** [j-hc/revanced-magisk-module#282]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**
Hi, 
i'm new to building things by myself, get it working as fork and changed the Config for my needs.
All Apps building fine, except the Music App. Did i miss anything or did something wrong?

```
username@username-virtual-machine:~/revanced-magisk-module_own$ sudo ./build.sh
[+] You are building locally. Magisk updates will not be enabled.
2023-07-21 11:19:32 URL:https://www.apkmirror.com/apk/google-inc/youtube/ [393479] -> "-" [1]
[+] Choosing version '18.25.40' for YouTube-Extended
[+] Building 'YouTube-Extended' in 'apk' mode
2023-07-21 11:19:32 URL:https://www.apkmirror.com/apk/google-inc/youtube/ [393480] -> "-" [1]
[+] Choosing version '18.23.35' for YouTube
[+] Building 'YouTube' in 'apk' mode
[+] Built YouTube-Extended (non-root): 'build/youtube-revanced-extended-v18.25.40-all.apk'
[+] Built YouTube (non-root): 'build/youtube-revanced-v18.23.35-all.apk'
2023-07-21 11:19:33 URL:https://www.apkmirror.com/apk/google-inc/youtube-music/ [258473] -> "-" [1]
2023-07-21 11:19:34 URL:https://www.apkmirror.com/uploads/?appcategory=youtube-music [268775] -> "-" [1]
[+] Choosing version '6.11.52' for Music
[+] Building 'Music' in 'apk' mode
[+] java -jar temp/jhc-rv/revanced-cli-2.23.0-all.jar --rip-lib x86_64 --rip-lib x86 --temp-dir=temp/tmp.fb5FNmk8WD -c -a temp/com.google.android.apps.youtube.music-6.11.52-arm64-v8a.apk -o temp/music-revanced-6.11.52-arm64-v8a-apk.apk -b temp/revanced-rv/revanced-patches-2.185.0.jar --keystore=ks.keystore   -m temp/revanced-rv/revanced-integrations-0.113.0.apk -i vanced-microg-support
2023-07-21 11:19:34 URL:https://www.apkmirror.com/apk/google-inc/youtube-music/ [258476] -> "-" [1]
2023-07-21 11:19:36 URL:https://www.apkmirror.com/uploads/?appcategory=youtube-music [268779] -> "-" [1]
[+] Choosing version '6.11.52' for Music-Extended
[+] Building 'Music-Extended' in 'apk' mode
[+] java -jar temp/jhc-rv/revanced-cli-2.23.0-all.jar --rip-lib x86_64 --rip-lib x86 --temp-dir=temp/tmp.GLMI6km9BZ -c -a temp/com.google.android.apps.youtube.music-6.11.52-arm64-v8a.apk -o temp/music-revanced-extended-6.11.52-arm64-v8a-apk.apk -b temp/inotia00-rv/revanced-patches-2.184.3.jar --keystore=ks.keystore   -m temp/inotia00-rv/revanced-integrations-0.112.3.apk -i microg-support
INFORMATION: Reading dex files 
INFORMATION: Reading dex files 
INFORMATION: Decoding AndroidManifest.xml only, because resources are not needed 
INFORMATION: Decoding AndroidManifest.xml only, because resources are not needed 
INFORMATION: Skipping change-package-name: Excluded by default 
INFORMATION: Skipping compact-header: Excluded by default 
INFORMATION: Skipping enable-android-debugging: Excluded by default 
INFORMATION: Skipping export-all-activities: Excluded by default 
INFORMATION: Skipping predictive-back-gesture: Excluded by default 
INFORMATION: Skipping remove-screen-capture-restriction: Excluded by default 
INFORMATION: Skipping remove-screenshot-restriction: Excluded by default 
INFORMATION: Skipping spoof-wifi-connection: Excluded by default 
INFORMATION: Skipping custom-branding-music-name: Excluded by default 
INFORMATION: Skipping custom-branding-icon-mmt: Excluded by default 
INFORMATION: Skipping custom-branding-icon-revancify-red: Excluded by default 
INFORMATION: Skipping enable-debug-logging: Excluded by default 
INFORMATION: Merging temp/inotia00-rv/revanced-integrations-0.112.3.apk 
INFORMATION: Deleting existing resource cache directory 
INFORMATION: Decoding resources 
INFORMATION: Deleting existing resource cache directory 
INFORMATION: Decoding resources 
INFORMATION: Executing patches 
INFORMATION: Background play succeeded 
INFORMATION: Bypass certificate checks succeeded 
INFORMATION: Codecs unlock succeeded 
INFORMATION: Exclusive audio playback succeeded 
INFORMATION: Hide get premium succeeded 
INFORMATION: Minimized playback music succeeded 
INFORMATION: Music video ads succeeded 
INFORMATION: Upgrade button remover succeeded 
INFORMATION: Vanced MicroG support succeeded 
INFORMATION: Compiling resources 
INFORMATION: Executing patches 
INFORMATION: Amoled succeeded 
INFORMATION: Background play succeeded 
INFORMATION: Bitrate default value succeeded 
INFORMATION: Certificate spoof succeeded 
INFORMATION: Custom branding icon Revancify blue succeeded 
INFORMATION: Custom package name succeeded 
INFORMATION: Disable auto captions succeeded 
INFORMATION: Enable black navigation bar succeeded 
INFORMATION: Enable color match player succeeded 
INFORMATION: Enable compact dialog succeeded 
INFORMATION: Enable custom filter succeeded 
INFORMATION: Enable dismiss queue succeeded 
INFORMATION: Enable force minimized player succeeded 
INFORMATION: Enable force shuffle succeeded 
INFORMATION: Enable landscape mode succeeded 
INFORMATION: Enable minimized playback succeeded 
INFORMATION: Enable new layout succeeded 
INFORMATION: Enable old style miniplayer succeeded 
INFORMATION: Enable opus codec succeeded 
INFORMATION: Enable sleep timer succeeded 
INFORMATION: Enable zen mode succeeded 
INFORMATION: Exclusive audio playback succeeded 
INFORMATION: Hide button shelf succeeded 
INFORMATION: Hide carousel shelf succeeded 
INFORMATION: Hide cast button succeeded 
INFORMATION: Hide category bar succeeded 
INFORMATION: Hide get premium succeeded 
INFORMATION: Hide music ads succeeded 
INFORMATION: Hide navigation label succeeded 
INFORMATION: Hide new playlist button succeeded 
INFORMATION: Hide playlist card succeeded 
INFORMATION: Hide taste builder succeeded 
INFORMATION: Hide upgrade button succeeded 
INFORMATION: Microg support succeeded 
INFORMATION: Optimize resource succeeded 
INFORMATION: Remember video quality succeeded 
INFORMATION: Settings succeeded 
INFORMATION: Share button hook succeeded 
INFORMATION: Spoof app version succeeded 
INFORMATION: Translations succeeded 
INFORMATION: Compiling resources 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6262: error: resource android:color/bright_foreground_dark_disabled is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6265: error: resource android:color/btn_default_material_dark is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6266: error: resource android:color/btn_leanback_color is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6267: error: resource android:color/bright_foreground_dark_inverse is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6268: error: resource android:color/btn_default_material_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6269: error: resource android:color/btn_leanback_focused is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6270: error: resource android:color/background_floating_device_default_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6271: error: resource android:color/background_device_default_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6272: error: resource android:color/car_action1 is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6273: error: resource android:color/car_action1_dark is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6274: error: resource android:color/background_holo_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6275: error: resource android:color/background_floating_material_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6276: error: resource android:color/car_blue_100 is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6277: error: resource android:color/car_blue_200 is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6278: error: resource android:color/bright_foreground_disabled_holo_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6279: error: resource android:color/accent_device_default_700 is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6280: error: resource android:color/btn_colored_borderless_text_material is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6281: error: resource android:color/bright_foreground_dark is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6282: error: resource android:color/background_material_dark is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/res/values/styles.xml:6283: error: resource android:color/car_blue_50 is private. 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_14806060400894206855989834218892100669.tmp, link, -o, /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL3739340255952186885.tmp, -0, arsc, -I, temp/tmp.fb5FNmk8WD/1.apk, --manifest, /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/AndroidManifest.xml, /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:21)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:173)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_14806060400894206855989834218892100669.tmp, link, -o, /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL3739340255952186885.tmp, -0, arsc, -I, temp/tmp.fb5FNmk8WD/1.apk, --manifest, /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/AndroidManifest.xml, /home/username/revanced-magisk-module_own/temp/tmp.fb5FNmk8WD/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 13 more
[+] Building 'Music' failed!
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6262: error: resource android:color/bright_foreground_dark_disabled is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6265: error: resource android:color/btn_default_material_dark is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6266: error: resource android:color/btn_leanback_color is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6267: error: resource android:color/bright_foreground_dark_inverse is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6268: error: resource android:color/btn_default_material_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6269: error: resource android:color/btn_leanback_focused is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6270: error: resource android:color/background_floating_device_default_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6271: error: resource android:color/background_device_default_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6272: error: resource android:color/car_action1 is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6273: error: resource android:color/car_action1_dark is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6274: error: resource android:color/background_holo_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6275: error: resource android:color/background_floating_material_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6276: error: resource android:color/car_blue_100 is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6277: error: resource android:color/car_blue_200 is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6278: error: resource android:color/bright_foreground_disabled_holo_light is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6279: error: resource android:color/accent_device_default_700 is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6280: error: resource android:color/btn_colored_borderless_text_material is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6281: error: resource android:color/bright_foreground_dark is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6282: error: resource android:color/background_material_dark is private. 
WARNUNG: /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/res/values/styles.xml:6283: error: resource android:color/car_blue_50 is private. 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_18031929074157997752126043921282089142.tmp, link, -o, /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL18006236728581300442.tmp, -0, arsc, -I, temp/tmp.GLMI6km9BZ/1.apk, --manifest, /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/AndroidManifest.xml, /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:21)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:173)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_18031929074157997752126043921282089142.tmp, link, -o, /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL18006236728581300442.tmp, -0, arsc, -I, temp/tmp.GLMI6km9BZ/1.apk, --manifest, /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/AndroidManifest.xml, /home/username/revanced-magisk-module_own/temp/tmp.GLMI6km9BZ/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 13 more
[+] Building 'Music-Extended' failed!
[+] Building mindetach module
/home/username/revanced-magisk-module_own/mindetach-magisk/mindetach /home/username/revanced-magisk-module_own
/home/username/revanced-magisk-module_own
[+] Done

```

```
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "apk"                                                   # 'both', 'apk' or 'module'
excluded-patches = ""                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default and only applies included-patches
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
build-mode = "apk"
excluded-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"                                                     # both arm64-v8a and arm-v7a

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"

[Twitter]
enabled = false
build-mode = "apk"
excluded-patches = "hide-views-stats"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"
```

**Comment by vcdwelt** [comment]
Okay, thanks for feedback.
