### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by gnadgnaoh** [j-hc/revanced-magisk-module#288]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**
[+] Choosing version '18.27.36' for YouTube-Extended
[+] Downloading 'YouTube-Extended' from APKMirror
2023-07-27 04:12:02 URL:https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-27-36-release/ [246179] -> "-" [1]
2023-07-27 04:12:02 URL:https://www.apkmirror.com/uploads/?appcategory=youtube-music [281040] -> "-" [1]
[+] Choosing version '6.12.53' for Music-Extended
[+] Downloading 'Music-Extended' from APKMirror
2023-07-27 04:12:03 URL:https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-27-36-release/youtube-18-27-36-android-apk-download/ [292450] -> "-" [1]
2023-07-27 04:12:03 URL:https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-6-12-53-release/ [247402] -> "-" [1]
2023-07-27 04:12:04 URL:https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-6-12-53-release/youtube-music-6-12-53-2-android-apk-download/ [292300] -> "-" [1]
2023-07-27 04:12:04 URL:https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-6-12-53-release/youtube-music-6-12-53-2-android-apk-download/download/?key=8b9069ce6686ca9e6209ff263bab02bfc0cf7d69&amp;forcebaseapk=true [279732] -> "-" [1]
wget: unable to resolve host address ‘www.apkmirror.comhttps’
[+] Building 'Music-Extended' in 'apk' mode
[+] java -jar temp/inotia00-rv/revanced-cli-2.22.2-all.jar --rip-lib x86_64 --rip-lib x86 --temp-dir=temp/tmp.1Is5gjtt2t -c -a temp/com.google.android.apps.youtube.music-6.12.53-arm64-v8a.apk -o temp/music-revanced-extended-6.12.53-arm64-v8a-apk.apk -b temp/inotia00-rv/revanced-patches-2.186.8.jar --keystore=ks.keystore -e custom-branding-music-name -e custom-branding-icon-mmt -e custom-branding-icon-revancify-blue -e custom-branding-icon-revancify-red  -m temp/inotia00-rv/revanced-integrations-0.114.8.apk -i microg-support
2023-07-27 04:12:05 URL:https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-27-36-release/youtube-18-27-36-android-apk-download/download/?key=575ea8b33dc9feb094467e8bf82aeea522d46be3&amp;forcebaseapk=true [277466] -> "-" [1]
wget: unable to resolve host address ‘www.apkmirror.comhttps’
[+] Building 'YouTube-Extended' in 'apk' mode
[+] java -jar temp/inotia00-rv/revanced-cli-2.22.2-all.jar --rip-lib x86_64 --rip-lib x86 --temp-dir=temp/tmp.goWn79qRly -c -a temp/com.google.android.youtube-18.27.36-all.apk -o temp/youtube-revanced-extended-18.27.36-all-apk.apk -b temp/inotia00-rv/revanced-patches-2.186.8.jar --keystore=ks.keystore -e custom-branding-youtube-name -e custom-branding-icon-mmt -e custom-branding-icon-revancify-blue -e custom-branding-icon-revancify-red -e enable-debug-logging  -m temp/inotia00-rv/revanced-integrations-0.114.8.apk -i microg-support
INFO: Reading dex files 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.android.tools.smali.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:90)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:53)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:43)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:66)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:50)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:41)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:35)
	at app.revanced.patcher.Patcher.<init>(Patcher.kt:62)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Error: utils.sh [-] Building 'Music-Extended' failed!
[-] Building 'Music-Extended' failed!

INFO: Reading dex files 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.android.tools.smali.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:90)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:53)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:43)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:66)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:50)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:41)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:35)
	at app.revanced.patcher.Patcher.<init>(Patcher.kt:62)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
[-] Building 'YouTube-Extended' failed!
Error: utils.sh [-] Building 'YouTube-Extended' failed!

[-] ABORT: All builds failed.
Error: utils.sh [-] ABORT: All builds failed.

Error: Process completed with exit code 1.

**Comment by vcdwelt** [comment]
After last commit is it working again, beside the Music Bug (Androlib is missing info for the M3 color of Android 14), but this seems a Revanced Patch issue.
