### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by gnadgnaoh** [j-hc/revanced-magisk-module#332]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**
INFO: Aligning com.google.android.youtube-18.36.39-all.apk 
java.io.IOException: KeyStore integrity check failed.
	at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineLoad(Unknown Source)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
	at app.revanced.library.ApkSigner.readKeyStore(ApkSigner.kt:165)
	at app.revanced.library.ApkUtils.sign(ApkUtils.kt:78)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:259)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
[-] Building 'YouTube-Extended' failed!
Error: utils.sh [-] Building 'YouTube-Extended' failed!

[-] ABORT: All builds failed.
Error: utils.sh [-] ABORT: All builds failed.

Error: Process completed with exit code 1.

**Comment by j-hc** [comment]
set cli source to my repo instead of inotia00 like i do in default config

**Comment by NormTurtle** [comment]
i tried it and it worked but one thing, 
ICONS , MMT icon patch is not working  , im talkign about non-varient MMT icon
here the [Release](https://github.com/NormTurtle/revanced-magisk-module/releases/tag/98)
and here the [patch-files](https://github.com/NormTurtle/revanced-magisk-module/blob/f48cb562b8e028a9a34e6cd40b64aa2cb69213a3/config.toml#L54)

### issue
![ic_launcher_round](https://github.com/j-hc/revanced-magisk-module/assets/108952834/77eb1ff0-96f1-407b-86a4-48c2c049920d)
^ this icon is comign which i dont watch :(
normal MMT icon patch is not working , 
its red or blue varient MMT icon
