### ISSUE TITLE
All builds failing

### ISSUE THREAD

**Issue by achyutde13** [j-hc/revanced-magisk-module#345]
**DO NOT REPORT REVANCED BUGS IN THIS REPO**
**Describe the bug of the rvmm builder or the modules**
Cannot build any app.
Log -

Building 'YouTube' in 'apk' mode
[+] java -jar temp/j-hc-rv/revanced-cli-4.0.2-all.jar patch temp/com.google.android.youtube-18.38.44-all.apk -r temp/tmp.tlGYVACJyd -p -o temp/youtube-revanced-18.38.44-all-apk.apk -b temp/revanced-rv/revanced-patches-2.196.0.jar --keystore=ks.keystore --keystore-entry-*** --keystore-*** --signer=jhc --alias=jhc -e "Swipe controls" -e "Enable debugging" -i "Custom branding" -m temp/revanced-rv/revanced-integrations-0.121.0.apk --rip-lib x86_64 --rip-lib x86 -i "Vanced MicroG support"
INFO: Loading patches 
Error: Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/fingerprint/MethodFingerprint
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at app.revanced.patches.messenger.ads.inbox.patch.HideInboxAdsPatch.<init>(HideInboxAdsPatch.kt:18)
	at app.revanced.patches.messenger.ads.inbox.patch.HideInboxAdsPatch.<clinit>(HideInboxAdsPatch.kt)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1113)
	at java.base/java.lang.reflect.Field.get(Field.java:425)
	at app.revanced.patcher.PatchBundleLoader$Utils.getInstance$revanced_patcher(PatchBundleLoader.kt:68)
	at app.revanced.patcher.PatchBundleLoader$3.invoke(PatchBundleLoader.kt:50)
	at app.revanced.patcher.PatchBundleLoader$3.invoke(PatchBundleLoader.kt:49)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll(MutableCollections.kt:129)
	at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt:54)
	at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt)
	at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt:33)
	at app.revanced.patcher.PatchBundleLoader$Jar.<init>(PatchBundleLoader.kt:94)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:197)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.fingerprint.MethodFingerprint
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 42 more
[-] Building 'YouTube' failed!
Error: utils.sh [-] Building 'YouTube' failed!

**Comment by emyaqin** [comment]
I guess that's ReVanced bugs, maybe, but its fixed now
