### ISSUE TITLE
Reddit Build Fail Error

### ISSUE THREAD

**Issue by Vucko130** [j-hc/revanced-magisk-module#443]
Reddit build is failing.
here is the log 
[logs_23990541527.zip](https://github.com/j-hc/revanced-magisk-module/files/15386928/logs_23990541527.zip)

here is the error

`WARNING: /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/apk/res/values/styles.xml:2661: error: expected enum but got (raw string) 0. 
WARNING: /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/apk/res/values/styles.xml:3268: error: expected enum but got (raw string) 1. 
WARNING: /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/apk/res/values/styles.xml:3271: error: expected enum but got (raw string) 1. 
WARNING: /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/apk/res/values/styles.xml:3303: error: expected enum but got (raw string) 1. 
WARNING: error: failed linking references. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_45524034455330100175319526121259585963.tmp, link, -o, /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1624969, --version-name, 2024.20.2, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /tmp/APKTOOL8253290714939946.tmp, -0, arsc, -I, /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/1.apk, --manifest, /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/apk/AndroidManifest.xml, /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:249)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:134)
	at app.revanced.patcher.Patcher.get(Patcher.kt:268)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:323)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_455[240](https://github.com/Vucko130/revanced-magisk-module/actions/runs/9167112947/job/25203735357#step:6:241)34455330100175319526121259585963.tmp, link, -o, /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1624969, --version-name, 2024.20.2, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /tmp/APKTOOL8253290714939946.tmp, -0, arsc, -I, /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/1.apk, --manifest, /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/apk/AndroidManifest.xml, /home/runner/work/revanced-magisk-module/revanced-magisk-module/temp/reddit-revanced-2024.20.2-all-temporary-files/patcher/apk/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:[245](https://github.com/Vucko130/revanced-magisk-module/actions/runs/9167112947/job/25203735357#step:6:246))
	... 13 more
[-] Building 'Reddit' failed!
Error: utils.sh [-] Building 'Reddit' failed!`

**Comment by j-hc** [comment]
> **DO NOT REPORT REVANCED STUFF IN THIS REPO**
