### ISSUE TITLE
Tiktok can't start

### ISSUE THREAD

**Issue by chrostino** [j-hc/revanced-magisk-module#472]
> **DO NOT REPORT REVANCED STUFF IN THIS REPO**  
if you delete these lines and proceed to report revanced stuff like **patch bugs** or **patch requests**, you will be **blocked** from this repo 
Use issues only to report bugs of the rvmm builder or the modules

I believe this is the right place to report this, if not I'll delete this post.
As per title the app barely starts then crashes, making it conpletely unusable
this is a log i caught of the crash
```
FATAL EXCEPTION: main
Process: com.zhiliaoapp.musically, PID: 12877
java.lang.VerifyError: Rejecting class com.ss.android.ugc.aweme.feed.panel.RecommendFeedFragmentPanel that attempts to sub-type erroneous class com.ss.android.ugc.aweme.feed.panel.FullFeedFragmentPanel (declaration of 'com.ss.android.ugc.aweme.feed.panel.RecommendFeedFragmentPanel' appears in /data/app/~~OmY1GZ0WTqRN94fdA5Cl2w==/com.zhiliaoapp.musically-TS3dR6Or5lcr-0SAftynQw==/base.apk!classes3.dex)
	at com.ss.android.ugc.aweme.feed.ui.FeedRecommendFragment.<init>(SourceFile:12)
	at com.ss.android.ugc.aweme.legoImp.task.PreloadInstanceMainActTask.run(SourceFile:16777378)
	at X.DRS.LJFF(SourceFile:16777307)
	at X.DQy.LIZJ(SourceFile:16777223)
	at Y.ARunnableS26S0200000_6.LIZ$31(SourceFile:77)
	at Y.ARunnableS26S0200000_6.run$112(SourceFile:16777216)
	at Y.ARunnableS26S0200000_6.run(Unknown Source:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at Y.ARunnableS26S0200000_6.run$88(SourceFile:16777230)
	at Y.ARunnableS26S0200000_6.run(Unknown Source:234)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.VerifyError: Rejecting class com.ss.android.ugc.aweme.feed.panel.FullFeedFragmentPanel that attempts to sub-type erroneous class com.ss.android.ugc.aweme.feed.panel.BaseListFragmentPanel (declaration of 'com.ss.android.ugc.aweme.feed.panel.FullFeedFragmentPanel' appears in /data/app/~~OmY1GZ0WTqRN94fdA5Cl2w==/com.zhiliaoapp.musically-TS3dR6Or5lcr-0SAftynQw==/base.apk!classes3.dex)
	... 12 more
Caused by: java.lang.VerifyError: Verifier rejected class com.ss.android.ugc.aweme.feed.panel.BaseListFragmentPanel: void com.ss.android.ugc.aweme.feed.panel.BaseListFragmentPanel.onRenderFirstFrame(java.lang.String) failed to verify: void com.ss.android.ugc.aweme.feed.panel.BaseListFragmentPanel.onRenderFirstFrame(java.lang.String): [0x1D] copyRes1 v2<- result0 type=Float (declaration of 'com.ss.android.ugc.aweme.feed.panel.BaseListFragmentPanel' appears in /data/app/~~OmY1GZ0WTqRN94fdA5Cl2w==/com.zhiliaoapp.musically-TS3dR6Or5lcr-0SAftynQw==/base.apk!classes24.dex)
	... 12 more
```

**Comment by j-hc** [comment]
revanced bug
