### ISSUE TITLE
Build Error: YouTube Music non-root armv7

### ISSUE THREAD

**Issue by rabilrbl** [j-hc/revanced-magisk-module#62]
Logs:
```bash
 Building Music arm-v7a
2022-09-29 14:54:57 URL:https://www.apkmirror.com/uploads/?appcategory=youtube-music [322345] -> "-" [1]
Choosing version '5.26.52'
2022-09-29 14:54:58 URL:https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-5-26-52-release/ [290855] -> "-" [1]
2022-09-29 14:54:58 URL:https://www.apkmirror.com/ [308668] -> "-" [1]
2022-09-29 14:54:58 URL:https://www.apkmirror.com/ [308623] -> "-" [1]
2022-09-29 14:54:58 URL:https://www.apkmirror.com/ [308614] -> "temp/music-stock-v5.26.52-arm-v7a.apk" [1]
INFO: Reading dex files 
org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Not a valid dex magic value: 3c 21 44 4f 43 54 59 50
	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:93)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:53)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:43)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:66)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:51)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:42)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:36)
	at app.revanced.patcher.Patcher.<init>(Patcher.kt:65)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:145)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Built Music (arm-v7a) (non-root)
```

**Comment by j-hc** [comment]
do you still get this error?

**Comment by rabilrbl** [comment]
Issue do not exist anymore.
