### ISSUE TITLE
Latest version of the cli is not compatible

### ISSUE THREAD

**Issue by Thunder-Mist** [j-hc/revanced-magisk-module#67]
Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/patch/BytecodePatch
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:13)
        at app.revanced.patcher.util.patch.impl.JarPatchBundle.loadPatches(JarPatchBundle.kt:13)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:140)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.BytecodePatch
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 22 more
getting error on building youtube  upon some search it belongs to revanced cli

**Comment by j-hc** [comment]
im aware. will fix it.

**Comment by j-hc** [comment]
> from [CLI Actions log](https://github.com/j-hc/revanced-cli/actions/runs/3195251441/jobs/5215690474#step:5:21)
> 
> looks like simplest "fix" is to revert this commit 🤔 [revanced/revanced-cli@839854d](https://github.com/revanced/revanced-cli/commit/839854d89062d46d698bf9b82b980cdeb37be857)

yes. i dont have access to my pc rn. will take a few hours.

**Comment by j-hc** [comment]
should be fixed now
